version: '3.8'

services:
  mantis-mcp:
    build: .
    container_name: mantis-mcp-server
    restart: unless-stopped
    ports:
      # Decoy service ports
      - "2121:2121"  # FTP
      - "2222:2222"  # SSH
      - "8080:8080"  # HTTP
      - "4445:4445"  # SMB
      - "2323:2323"  # Telnet
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CALLBACK_IP=${CALLBACK_IP:-10.0.0.1}
      - CALLBACK_PORT=${CALLBACK_PORT:-7777}
      - INJECTION_THRESHOLD=${INJECTION_THRESHOLD:-0.6}
      - ENABLE_TARPIT=${ENABLE_TARPIT:-true}
      - TARPIT_COMPLEXITY=${TARPIT_COMPLEXITY:-5}
    volumes:
      - ./logs:/app/logs
      - ./mantis_config.json:/app/mantis_config.json
    networks:
      - mantis-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW

networks:
  mantis-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16